### ISSUE TITLE
Improve Smart coffee machine tutorial

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.website#13]
see http://www.thingweb.io/smart-coffee-machine.html

I suggest we change

`title: 'Smart Coffee Machine'`
to
`title: 'Smart-Coffee-Machine'`

(changing spaces with -)

Doing so helps to get rid of all these %20 characters for space in tutorial that just confuses people what it is for. 
What do you think @fatadel?
Can we update the tutorial on the website and the according example in node-wot?

**Comment by fatadel** [comment]
@danielpeintner 
We definitely can update the tutorial and the respective files with your suggestion, but I was relying on the description of the `title` field from W3C TD document (https://www.w3.org/TR/wot-thing-description/#thing), which says:
"Provides a human-readable title (e.g., display a text for UI representation) based on a default language."
So, if I had a UI I would rather like to see "Smart Coffee Machine" on it, than "Smart-Coffee-Machine", since the former is more "human-readable title" for me. But I do also understand your point here. Should we maybe discuss the way the URIs are generated?

**Comment by danielpeintner** [comment]
@sebastiankb any opinion?

> Should we maybe discuss the way the URIs are generated?

I think the URI generation is fine. A space gets turned into `%20` on each URI (see https://www.urlencoder.org/).

My argument was just that it looks *silly* for the first tutorial people might look at.

**Comment by sebastiankb** [comment]
I can understand both sides. Indeed, when it comes to the URL it looks quite strange and maybe needs more explanation. If it is not so much effort, lets follow Daniel's suggestion and have the whitespaces replaced with -.

**Comment by fatadel** [comment]
Okay, I will do it today.

**Comment by fatadel** [comment]
https://github.com/eclipse/thingweb.node-wot/pull/227
https://github.com/eclipse/thingweb.website/pull/14

**Comment by danielpeintner** [comment]
Thanks @fatadel
